In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.4.1


In [3]:
hello = tf.constant('Hello ')

In [4]:
world = tf.constant('World')

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'Hello World'


In [10]:
a = tf.constant(10)
b = tf.constant(20)

In [11]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [12]:
result

30

In [13]:
const = tf.constant(10)

In [14]:
fill_mat = tf.fill((4,4),10)

In [15]:
myzeros = tf.zeros((4,4))

In [16]:
myones = tf.ones((4,4))

In [17]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [18]:
my_randu = tf.random_uniform((4,4),minval=0,maxval=1)

In [20]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,my_randu]

In [21]:
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    #print(sess.run(op))
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 1.1129204   0.42906433  0.46940291  0.75166649]
 [-0.12992239  0.88569391  0.10672257 -0.95369583]
 [ 1.82816947  0.67565608 -0.43910185  0.15661548]
 [-1.04161167 -1.21850085  1.97660768 -0.59579515]]


[[ 0.75944185  0.85541677  0.57277071  0.80675745]
 [ 0.89093924  0.18385363  0.27547133  0.96722007]
 [ 0.01951814  0.33374524  0.25151026  0.79575217]
 [ 0.95031595  0.94841337  0.23184729  0.75694227]]




In [26]:
a = tf.constant([ [1,2],[3,4]])

In [27]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [28]:
b = tf.constant([[10],[100]])

In [29]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [30]:
result = tf.matmul(a,b)

In [31]:
sess.run(result)

array([[210],
       [430]], dtype=int32)